import type { Listing } from "@/clients/listings";

export const makeListing = (overrides: Partial<Listing> = {}): Listing => ({
  uid: 1,
  name: "Sunrise Apartments",
  address: "221 King Street",
  city: "Clifton",
  state: "NJ",
  zipCode: "08608",
  rent: 1200,
  rentMax: null,
  bedrooms: 2,
  bathrooms: 1,
  unitType: null,
  imageId: null,
  imageUrl: null,
  photoKeys: [],
  phoneNumber: "914-693-6613",
  website: null,
  description: null,
  lastUpdated: null,
  isWaitlistOpen: true,
  amenities: [],
  contactName: null,
  contactOrganization: null,
  fullListingUrl: "https://www.myhousingsearch.com/listing/1",
  rentType: null,
  depositRange: null,
  legacyDetails: null,
  ...overrides,
});
