name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  biome:
    uses: ./.github/workflows/biome.yml
  unit-tests:
    uses: ./.github/workflows/unit_tests.yml
