name: ci

on:
  pull_request:
    branches:
      - "main"
      - "dev"
  push:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  biome:
    uses: ./.github/workflows/biome.yml
  unit-tests:
    uses: ./.github/workflows/unit_tests.yml
  db-tests:
    uses: ./.github/workflows/db_tests.yml
